"""add_contact_model_and_normalize_email_messages

Revision ID: 1d9717169cfa
Revises: 
Create Date: 2024-12-02 23:05:21.513281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9717169cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the contact table
    op.create_table('contact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('normalized_email', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_contact'),
        sa.UniqueConstraint('email', name='uq_contact_email'),
        sa.UniqueConstraint('normalized_email', name='uq_contact_normalized_email')
    )

    # Then modify the email_message table while preserving existing indexes
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('from_contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_contact_id', sa.Integer(), nullable=True))
        
        # Create new indexes for contact relations
        batch_op.create_index('ix_email_message_from_contact', ['from_contact_id'], unique=False)
        batch_op.create_index('ix_email_message_to_contact', ['to_contact_id'], unique=False)
        
        # Add foreign key constraints with explicit names
        batch_op.create_foreign_key(
            'fk_email_message_from_contact',
            'contact', ['from_contact_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_email_message_to_contact',
            'contact', ['to_contact_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_email_message_from_contact', type_='foreignkey')
        batch_op.drop_constraint('fk_email_message_to_contact', type_='foreignkey')
        batch_op.drop_index('ix_email_message_from_contact')
        batch_op.drop_index('ix_email_message_to_contact')
        batch_op.drop_column('to_contact_id')
        batch_op.drop_column('from_contact_id')

    op.drop_table('contact')
    # ### end Alembic commands ###
