"""add_body_hash_and_preview

Revision ID: 206063017c9c
Revises: 60c71866c589
Create Date: 2024-12-04 02:13:09.762554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206063017c9c'
down_revision = '60c71866c589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_hash', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('body_preview', sa.String(length=1000), nullable=True))
        batch_op.drop_index('idx_email_message_content_hash')
        batch_op.create_index('idx_email_message_content_hash', ['body_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index('idx_email_message_content_hash')
        batch_op.create_index('idx_email_message_content_hash', [sa.text('md5(body)')], unique=False)
        batch_op.drop_column('body_preview')
        batch_op.drop_column('body_hash')

    # ### end Alembic commands ###
