"""add_fulltext_search_and_optimize_indexes

Revision ID: 60c71866c589
Revises: 87c60f7c2b7c
Create Date: 2024-12-04 02:09:01.162613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c71866c589'
down_revision = '87c60f7c2b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index('idx_email_message_content')
        batch_op.create_index('idx_email_message_content_hash', [sa.text('md5(body::text)')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index('idx_email_message_content_hash')
        batch_op.create_index('idx_email_message_content', ['subject', 'body'], unique=False)

    # ### end Alembic commands ###
