"""empty message

Revision ID: 7b2ff1eaff99
Revises: 1d9717169cfa
Create Date: 2024-12-02 23:09:39.362233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2ff1eaff99'
down_revision = '1d9717169cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing records to ensure data consistency
    op.execute("""
        CREATE TEMPORARY TABLE _email_temp AS 
        SELECT DISTINCT from_address as email 
        FROM email_message 
        WHERE from_address IS NOT NULL
        UNION 
        SELECT DISTINCT to_address 
        FROM email_message 
        WHERE to_address IS NOT NULL
    """)
    
    op.execute("""
        INSERT INTO contact (email, normalized_email)
        SELECT email, lower(trim(email))
        FROM _email_temp
        WHERE email NOT IN (SELECT email FROM contact)
    """)
    
    # Drop temporary table
    op.execute("DROP TABLE _email_temp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index('ix_email_message_to_address')
        batch_op.drop_index('ix_email_message_from_address')

    # ### end Alembic commands ###
