"""add_contact_model_and_normalize_email_fields

Revision ID: a0808c78ca16
Revises: 
Create Date: 2024-12-02 23:58:35.864066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0808c78ca16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index('idx_contact_normalized_email')

    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_index('idx_email_message_from_contact')
        batch_op.drop_index('idx_email_message_to_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.create_index('idx_email_message_to_contact', ['to_contact_id'], unique=False)
        batch_op.create_index('idx_email_message_from_contact', ['from_contact_id'], unique=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index('idx_contact_normalized_email', ['normalized_email'], unique=False)

    # ### end Alembic commands ###
